# Generated by Django 5.2.1 on 2025-05-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonVisiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=100)),
                ('visit_reason', models.CharField(max_length=100)),
                ('visit_start_time', models.DateTimeField()),
                ('visit_end_time', models.DateTimeField()),
                ('visitor_group', models.PositiveIntegerField()),
                ('respondent', models.CharField(max_length=100)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_info', to='apps.person')),
            ],
        ),
    ]
