# Generated by Django 5.2.1 on 2025-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_personvisiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvisiting',
            name='visitor_group',
            field=models.CharField(max_length=10),
        ),
    ]
