# Generated by Django 5.2.1 on 2025-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_personvisiting_visitor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personimage',
            name='image_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
