# Generated by Django 5.2.1 on 2025-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='personimage',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
