# Generated by Django 5.2.1 on 2025-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_personimage_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_port',
            field=models.PositiveIntegerField(default=554),
        ),
    ]
