# Generated by Django 5.2.1 on 2025-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_camera_cam_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_port',
            field=models.PositiveIntegerField(),
        ),
    ]
