# Generated by Django 5.2.1 on 2025-06-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_camera_cam_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cam_port',
        ),
    ]
