# Generated by Django 5.2.1 on 2025-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_camera_cam_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cam_id', models.CharField(max_length=100)),
                ('cam_position', models.CharField(default='Local PC', max_length=100)),
                ('registered_image', models.ImageField(upload_to='registered_images/')),
                ('live_capture', models.ImageField(upload_to='live_captures/')),
                ('status', models.CharField(choices=[('Granted', 'Granted'), ('Denied', 'Denied')], max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
