# Generated by Django 5.2.1 on 2025-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvisiting',
            name='visit_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personvisiting',
            name='visit_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
